name: Fast Forward Merge PR
on:
  issue_comment:
    types: created

jobs:
   pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Fast Forward PR
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          success_message: succesffuly merged
          failure_message: failed merging
